services:
  postgres:
    image: postgres:17-alpine
    container_name: db_marvi
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5

  api:
    build: .
    container_name: marvi-api-v2
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "3000:3000"
    environment:
      PORT: ${PORT}
      PUBLIC_URL: ${PUBLIC_URL}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_HOST: postgres
      DB_PORT: ${DB_PORT}
      DB_NAME: ${DB_NAME}
      USER_EMAIL: ${USER_EMAIL}
      PASSWORD_EMAIL: ${PASSWORD_EMAIL}
      JWT_SECRET: ${JWT_SECRET}
      JWT_EXPIRES: ${JWT_EXPIRES}
      CLOUDINARY_CLOUD_NAME: ${CLOUDINARY_CLOUD_NAME}
      CLOUDINARY_API_KEY: ${CLOUDINARY_API_KEY}
      CLOUDINARY_API_SECRET: ${CLOUDINARY_API_SECRET}
      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
      STRIPE_SECRET_KEY: ${STRIPE_SECRET_KEY}
      STRIPE_WEBHOOK_SECRET: ${STRIPE_WEBHOOK_SECRET}
    command: sh -c "npm start"

  stripe:
    image: stripe/stripe-cli:latest
    container_name: stripe-webhooks
    environment:
      STRIPE_SECRET_KEY: ${STRIPE_SECRET_KEY}
    depends_on:
      - api
    entrypoint: >
      sh -c "
      stripe login --api-key ${STRIPE_SECRET_KEY} &&
      stripe listen --forward-to http://api:3000/webhook
      "

volumes:
  postgres_data:
